import Header from "@/components/Header";
import "../globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Cursor from "@/components/Cursor";
import { site, SITE_URL } from "@/lib/site";
import { locales, localeDirections, isLocale } from "@/i18n/config";
import { getMessages } from "@/i18n";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${site.name} — ${site.tagline}`,
    template: `%s — ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  keywords: [
    "web development",
    "web design",
    "e-commerce development",
    "custom web applications",
    "Next.js development",
    "web development Algeria",
  ],
  authors: [{ name: "Sadjed Bougandoura" }, { name: "Abd Eldjalil Selamnia" }],
  creator: site.name,
  publisher: site.name,
  openGraph: {
    type: "website",
    siteName: site.name,
    title: `${site.name} — ${site.tagline}`,
    description: site.description,
    url: "/",
  },
  twitter: {
    card: "summary_large_image",
    title: `${site.name} — ${site.tagline}`,
    description: site.description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
};

// LayoutProps is generated by `next typegen`, so the params shape is derived
// from the route rather than hand-written and able to drift from it.
export default async function RootLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  // Next 16: params is a Promise; synchronous access was removed.
  const { locale } = await params;
  if (!isLocale(locale)) notFound();

  const messages = await getMessages(locale);

  return (
    // Next 16 no longer overrides `scroll-behavior: smooth` on navigation
    // unless this attribute is present.
    <html
      lang={locale}
      dir={localeDirections[locale]}
      data-scroll-behavior="smooth"
      className={inter.className}
    >
      <body className="overflow-x-hidden">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[60] focus:rounded focus:bg-ink focus:px-4 focus:py-2 focus:text-paper"
        >
          {messages.nav.skipToContent}
        </a>
        <span id="top" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "ProfessionalService",
              name: site.name,
              description: site.description,
              url: SITE_URL,
              image: `${SITE_URL}/opengraph-image`,
              address: {
                "@type": "PostalAddress",
                addressCountry: site.country,
              },
              founder: [
                { "@type": "Person", name: "Sadjed Bougandoura", jobTitle: "Chief Executive Officer" },
                { "@type": "Person", name: "Abd Eldjalil Selamnia", jobTitle: "Co-Founder" },
              ],
              sameAs: Object.values(site.social),
              serviceType: [
                "Web development",
                "Web design",
                "E-commerce development",
                "Custom web application development",
              ],
            }),
          }}
        />
        <Cursor />
        <Header locale={locale} messages={messages.nav} />
        {children}
      </body>
    </html>
  );
}
